name: auto-approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'bglw' && github.repository == 'pagefind/pagefind'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 # v4.0.1
        with:
          application_id: ${{ secrets.PF_BOT_ID }}
          application_private_key: ${{ secrets.PF_BOT_PEM }}
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
